name: a

on:
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checkstyle
        working-directory: spring-petclinic
        run: mvn checkstyle:checkstyle

      - name: Save checkstyle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: spring-petclinic/checkstyle-result.xml
  
  test:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        working-directory: spring-petclinic
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build without tests
        working-directory: spring-petclinic
        run: mvn clean install -DskipTests

  docker:
    runs-on: ubuntu-latest
    needs: [checkstyle, test, build]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mr:${{ github.sha }} .
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mr:${{ github.sha }}